import{a as f,S as p,i}from"./assets/vendor-tnUJPedx.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(r){if(r.ep)return;r.ep=!0;const t=s(r);fetch(r.href,t)}})();const u="48879708-f080042100b5dbafec10d9d0f",m="https://pixabay.com/api/";async function d(o){try{return(await f.get(m,{params:{key:u,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(e){return console.error("Error fetching images:",e),[]}}function y(o){return o.map(e=>`<a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
      <div class="info">
        <p class ="info-item">Likes <span class="info-amount">${e.likes}</span></p>
        <p class ="info-item">Views <span class="info-amount">${e.views}</span></p>
        <p class ="info-item">Comments <span class="info-amount">${e.comments}</span></p>
        <p class ="info-item">Downloads <span class="info-amount">${e.downloads}</span></p>
      </div>
    </a>`).join("")}const g=document.querySelector("#search-form"),l=document.querySelector(".gallery"),a=document.querySelector(".loader"),h=new p(".gallery a");g.addEventListener("submit",async o=>{o.preventDefault();const e=o.target.elements.searchQuery.value.trim();if(!e){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}a.style.display="block",l.innerHTML="";try{const s=await d(e);if(a.style.display="none",s.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query!",position:"topRight"});return}l.innerHTML=y(s),h.refresh()}catch{a.style.display="none",i.error({title:"Error",message:"An error occurred while fetching images!",position:"topRight"})}});
//# sourceMappingURL=index.js.map
